# Generated by Django 4.2.2 on 2023-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='data_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
