# Generated by Django 4.2.2 on 2023-06-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convidado',
            old_name='user',
            new_name='usuario',
        ),
    ]
